### ISSUE TITLE
Ban implicit dynamic

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#719]
The Dart analyzer has options for preventing `dynamic` from appearing in the code accidentally:
https://dart.dev/tools/analysis#enabling-additional-type-checks
They look like this in `analysis_options.yaml`:
```yaml
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
```

The Flutter tree enables those options. We should too — we've often had little surprises where something turns out to have been `dynamic` because we were a bit sloppy in writing down types. (No live bugs yet, as far as I can recall, but clearly the potential for some.)
